@baseUrl = https://localhost:7081
@difficultyId = 8c936d6d-1060-4efb-9480-7ac8abd7d275

### get all difficulties
GET {{baseUrl}}/api/difficulties


### get difficulty by id
GET {{baseUrl}}/api/difficulties/{{difficultyId}}

### create new difficulty
POST {{baseUrl}}/api/difficulties
Content-Type: application/json

{
  "Name": "New Difficult2y2222222"
}

### update difficulty
PUT {{baseUrl}}/api/difficulties/{{difficultyId}}
Content-Type: application/json

{
  "Name": "Updated Difficulty"
}

### delete difficulty
DELETE {{baseUrl}}/api/difficulties/{{difficultyId}}


////////////////////////////////////////////////////

@regionId = 2fd0fc1b-3064-44ba-a121-ed1bddabf7df

### get all regions
GET {{baseUrl}}/api/regions


### get region by id
GET {{baseUrl}}/api/regions/{{regionId}}

### create new region
POST {{baseUrl}}/api/regions
Content-Type: application/json

{
  "Name": "New Region23ss2",
  "Code": "NEW-REGION"
}

### update region
PUT {{baseUrl}}/api/regions/{{regionId}}
Content-Type: application/json

{
  "Name": "Updated Region",
  "Code": "UPDATED-REGION",
  "imageUrl": "https://example.com/updated-region-image.jpg"
}

### delete region
DELETE {{baseUrl}}/api/regions/{{regionId}}


////////////////////////////////////////////////////

@walkId = eb4ae35d-7282-4497-a772-4fa2bb26b0da

### get all Walks
GET {{baseUrl}}/api/walks?pageNumber=1&pageSize=2


### get Walk by id
GET {{baseUrl}}/api/walks/{{walkId}}

### create new Walk
POST {{baseUrl}}/api/walks
Content-Type: application/json

{
  "Name": "New Walk",
  "Description": "A new walk",
  "LengthInKm": 5.0,
  "DifficultyId": "{{difficultyId}}",
  "RegionId": "{{regionId}}",
  "imageUrl": "https://example.com/new-walk-image.jpg"
}

### update Walk
PUT {{baseUrl}}/api/walks/{{walkId}}
Content-Type: application/json

{
  "Name": "Updated Walk",
  "Description": "An updated walk",
  "LengthInKm": 6.0,
  "DifficultyId": "{{difficultyId}}",
  "RegionId": "{{regionId}}",
  "imageUrl": "https://example.com/updated-walk-image.jpg"
}

### delete Walk
DELETE {{baseUrl}}/api/walks/{{walkId}}