@baseUrl = https://localhost:7081
@difficultyId = 64c8c1a2-19e5-46b4-ba64-38e9af652891

### get all difficulties
GET {{baseUrl}}/api/difficulties


### get difficulty by id
GET {{baseUrl}}/api/difficulties/{{difficultyId}}

### create new difficulty
POST {{baseUrl}}/api/difficulties
Content-Type: application/json

{
  "Name": "New Difficult2y332222233222"
}

### update difficulty
PUT {{baseUrl}}/api/difficulties/{{difficultyId}}
Content-Type: application/json

{
  "Name": "Updated Difficulty333222"
}

### delete difficulty
DELETE {{baseUrl}}/api/difficulties/{{difficultyId}}


////////////////////////////////////////////////////

@regionId = 2fd0fc1b-3064-44ba-a121-ed5bddabf7df

### get all regions
GET {{baseUrl}}/api/regions


### get region by id
GET {{baseUrl}}/api/regions/{{regionId}}

### create new region
POST {{baseUrl}}/api/regions
Content-Type: application/json

{
  "Name": "New Region23ss2",
  "Code": "NEW-REGION"
}

### update region
PUT {{baseUrl}}/api/regions/{{regionId}}
Content-Type: application/json

{
  "Name": "Updated Region",
  "Code": "UPDATED-REGION",
  "imageUrl": "https://example.com/updated-region-image.jpg"
}

### delete region
DELETE {{baseUrl}}/api/regions/{{regionId}}


////////////////////////////////////////////////////

@walkId = 132caba3-de04-46f3-adc6-a4856a798972

### get all Walks
@pageNumber = 1
@pageSize = 2

GET {{baseUrl}}/api/walks?pageNumber={{pageNumber}}&pageSize={{pageSize}}


### get Walk by id
GET {{baseUrl}}/api/walks/{{walkId}}

### create new Walk
POST {{baseUrl}}/api/walks
Content-Type: application/json

{
  "Name": "New Walk",
  "Description": "A new walk",
  "LengthInKm": 5.0,
  "DifficultyId": "{{difficultyId}}",
  "RegionId": "{{regionId}}",
  "imageUrl": "https://example.com/new-walk-image.jpg"
}

### update Walk
PUT {{baseUrl}}/api/walks/{{walkId}}
Content-Type: application/json

{
  "Name": "Updated Walk",
  "Description": "An updated walk",
  "LengthInKm": 6.0,
  "DifficultyId": "{{difficultyId}}",
  "RegionId": "{{regionId}}",
  "imageUrl": "https://example.com/updated-walk-image.jpg"
}

### delete Walk
DELETE {{baseUrl}}/api/walks/{{walkId}}